- name: Install Vietnames input method
  aur:
    name: ibus-bamboo
    state: present

- name: Set ibus config
  dconf:
    key: "/desktop/ibus/{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ ibus_config | dict2items }}"
