- name: Install development tools
  become: yes
  pacman:
    name:
      - gimp
      - go
      - helm
      - kubectl
      - kustomize
      - rust
      - terraform
      - terragrunt
    state: present

- name: Install development tools from the AUR
  kewlfft.aur.aur:
    name:
      - cloudflared-bin
      - lens-bin
      - kind
    state: present
