- name: Install dotfiles packages
  become: yes
  pacman:
    name:
      - alsa-utils
      - arandr
      - autorandr
      - bspwm
      - dunst
      - firefox
      - fzf
      - git
      - light
      - maim
      - nnn
      - nodejs
      - playerctl
      - ripgrep
      - sxhkd
      - tmux
      - xclip
      - xdotool
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xsetroot
      - zsh
    state: present

- name: Install dotfiles packages from the AUR
  aur:
    name:
      - neovim-git # TODO use stable version of Neovim when 0.5 is out
      - nerd-fonts-fira-code
      - picom-git
      - polybar
    state: present

- name: Clone custom packages source code
  git:
    repo: "https://github.com/khuedoan/{{ item }}"
    dest: "~/.local/src/{{ item }}"
  loop:
    - dmenu
    - slock
    - st
  register: custom_packages_sources

- name: Install custom packages
  become: yes
  make:
    chdir: "{{ item.invocation.module_args.dest }}"
    target: install
  loop: "{{ custom_packages_sources.results }}"
