- name: Install packages
  become: yes
  pacman:
    name:
      - dunst
      - firefox
      - fzf
      - git
      - interception-caps2esc
      - light
      - maim
      - nnn
      - nodejs
      - tmux
      - ripgrep
      - xclip
      - xorg-server
      - xorg-xinit
      - zsh
    state: present

- name: Install packages from the AUR
  aur:
    name:
      - nerd-fonts-fira-code
      - picom-git
      - neovim-git # TODO use stable version of Neovim when 0.5 is out

- name: Clone custom packages source code
  git:
    repo: "https://github.com/khuedoan/{{ item }}"
    dest: "~/.local/src/{{ item }}"
  loop:
    - dmenu
    - dwm
    - slock
    - st
  register: custom_packages_source

- name: Install custom packages
  become: yes
  make:
    chdir: "{{ item.invocation.module_args.dest }}"
    target: install
  loop: "{{ custom_packages_source.results }}"
