- name: Install dotfiles packages
  become: yes
  pacman:
    name:
      - alsa-utils
      - arandr
      - autorandr
      - bat
      - bspwm
      - dunst
      - feh
      - firefox
      - fzf
      - git
      - light
      - maim
      - neovim
      - nnn
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - npm
      - pcmanfm-gtk3
      - playerctl
      - ripgrep
      - sxhkd
      - tmux
      - xclip
      - xdotool
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xsetroot
      - zsh
    state: present

- name: Change default shell to Zsh
  become: yes
  user:
    user: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install dotfiles packages from the AUR
  aur:
    name:
      - nerd-fonts-fira-code
      - picom-git
      - polybar
    state: present

- name: Clone custom packages source code
  git:
    repo: "https://github.com/khuedoan/{{ item }}"
    dest: "~/.local/src/{{ item }}"
  loop:
    - dmenu
    - slock
    - st
  register: custom_packages_sources

- name: Install custom packages
  become: yes
  make:
    chdir: "{{ item.invocation.module_args.dest }}"
    target: install
  loop: "{{ custom_packages_sources.results }}"
