- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "~"

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "~"
    value: "no"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "~"
  register: add_remote
  failed_when: add_remote.rc != 0 and "already exist" not in add_remote.stderr

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "~"
    update: yes

- name: Clone zsh plugin manager
  git:
    repo: "https://github.com/zdharma/zinit.git"
    dest: "~/.zsh/zinit"
    depth: 1

- name: Clone neovim package manager
  git:
    repo: "https://github.com/savq/paq-nvim.git"
    dest: "~/.local/share/nvim/site/pack/paqs/opt/paq-nvim"
    depth: 1
