- name: Init empty dotfiles repo
  command: "git init"
  args:
    chdir: "~"

- name: Disable show untracked files
  git_config:
    name: "status.showUntrackedFiles"
    scope: local
    repo: "~"
    value: "no"

- name: Add remote repository
  command: "git remote add origin {{ dotfiles_repo }}"
  args:
    chdir: "~"
  register: add_remote
  failed_when: add_remote.rc != 0 and "already exist" not in add_remote.stderr

- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "~"
    update: yes

- name: Clone zsh plugin manager
  git:
    repo: "https://github.com/zdharma-continuum/zinit.git"
    dest: "~/.zsh/zinit"
    depth: 1

- name: Clone neovim package manager
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

- name: Ensures wallpaper directory exist
  file:
    path: ~/Pictures/Wallpapers
    state: directory

- name: Download wallpaper
  get_url:
    url: https://user-images.githubusercontent.com/27996771/129466074-64c92948-96b0-4673-be33-75ee26b82a6c.jpg
    dest: ~/Pictures/Wallpapers/LostInMindNord.jpg
